FROM python:3.11-slim-bookworm

# Setting the working directory in the container
WORKDIR /app

# Copying backend requirements and install them
COPY backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copying the entire backend application code
COPY backend/ ./backend/

# Exposing the port FastAPI will run on
EXPOSE 8000


CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]